---
- name: Ensure node_exporter user exists
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    shell: /usr/sbin/nologin
    create_home: no
    system: yes
 
- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter.tar.gz"
    mode: '0644'
    checksum: "sha256:{{ node_exporter_tar_checksum }}"
 
- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp"
    remote_src: yes
  args: # Extract if not already extracted
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
 
- name: Move Node Exporter binary to install path
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_install_path }}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_user }}"
    mode: '0755'
    remote_src: yes
    force: no  # Only copy if the destination file is different
 
- name: Create systemd service for Node Exporter
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'
  notify:
    - Reload systemd
    - Restart Node Exporter
 
- name: Enable and start Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
